// Replace the placeholder values with real config generated by
// `flutterfire configure` or from your Firebase console.
// This keeps the app compiling while you wire in the correct values.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFphIPB0069unY_uukhlMdK-puecXCbw',
    appId: '1:416804470692:android:534c5bc0cd77e243ddcb31',
    messagingSenderId: '416804470692',
    projectId: 'push-notification-demo-fe62a',
    storageBucket: 'push-notification-demo-fe62a.firebasestorage.app',
  );

  // TODO: fill with values from your Firebase project.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.trael_app_abdelhamid',
  );

  // TODO: fill with values from your Firebase project.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.trael_app_abdelhamid',
  );
}
