// Replace the placeholder values with real config generated by
// `flutterfire configure` or from your Firebase console.
// This keeps the app compiling while you wire in the correct values.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF5TXcltxOK4IhV8jPUF-SK17SoNb9_-s',
    appId: '1:963480007795:android:bd697f631cb5338689e606',
    messagingSenderId: '963480007795',
    projectId: 'temheed-275c8',
    storageBucket: 'temheed-275c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cBKG8YV2oNcsElcChXhnvjazzXjFmHY',
    appId: '1:963480007795:ios:0b2b79946d6e4f1a89e606',
    messagingSenderId: '963480007795',
    projectId: 'temheed-275c8',
    storageBucket: 'temheed-275c8.firebasestorage.app',
    iosBundleId: 'com.temheed.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cBKG8YV2oNcsElcChXhnvjazzXjFmHY',
    appId: '1:963480007795:ios:0b2b79946d6e4f1a89e606',
    messagingSenderId: '963480007795',
    projectId: 'temheed-275c8',
    storageBucket: 'temheed-275c8.firebasestorage.app',
    iosBundleId: 'com.temheed.ios',
  );
}
